[package]
name = "solar"
version = "0.0.1"
authors = ["ed"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.17.0"
crossterm = "0.22.1"
